### ISSUE TITLE
Request support for cortex-m3 and cortex-m4

### ISSUE THREAD

**Issue by retif** [ycoroneos/G.E.R.T#3]
Lots of affordable development boards are available on the market with those chips.

**Comment by ycoroneos** [comment]
Cortex M3s and M4s use thumb instructions, which the go compiler can't generate. Also, GERT is cooperatively scheduled so explicit yield()'s must be sprinkled around when running it on a single-core. I would also like to bring gert to cortex M's one day when the go compiler can generate thumb.
