### ISSUE TITLE
Laser projector hardware

### ISSUE THREAD

**Issue by davidhtims** [ycoroneos/G.E.R.T#5]
Reading your paper ...
Could you point me to a laser projector module to experiment with please?

**Comment by ycoroneos** [comment]
The galvos and driver I used are from seeed (https://www.seeedstudio.com/Galvanometer-motor-%28SC17-15K%29-p-2024.html). This is the cheapest commercial galvo set I have found

**Comment by ycoroneos** [comment]
I still use these galvos and they're still the cheapest. Closing the issue.
